# Generated by Django 6.1.1 on 2026-09-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('adresse', models.TextField(blank=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_nom', models.CharField(max_length=200)),
                ('hotel_adresse', models.TextField()),
                ('hotel_ville', models.CharField(max_length=100)),
                ('hotel_telephone', models.CharField(max_length=20)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('hotel_description', models.TextField()),
                ('hotel_photo', models.ImageField(blank=True, null=True, upload_to='demandes/hotels/')),
                ('hotel_photos_supp', models.JSONField(blank=True, default=list)),
                ('proprietaire_photo', models.ImageField(blank=True, null=True, upload_to='demandes/proprietaires/')),
                ('documents', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Madagascar', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email_contact', models.EmailField(max_length=254)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('photos_supplementaires', models.JSONField(blank=True, default=list)),
                ('est_actif', models.BooleanField(default=False)),
                ('est_visible', models.BooleanField(default=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_nuits', models.IntegerField()),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_admin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYEE', 'Payée - En attente de validation'), ('CONFIRMEE', 'Confirmée par le propriétaire'), ('REFUSEE', 'Refusée par le propriétaire'), ('ANNULEE', 'Annulée par le client'), ('EXPIREE', 'Expirée'), ('ECHEC_PAIEMENT', 'Échec du paiement')], default='EN_ATTENTE', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.client')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.hotel')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESERVATION', 'Réservation'), ('PAIEMENT', 'Paiement'), ('VALIDATION', 'Validation'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=20)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.client')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='api.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('SUPERIEUR', 'Supérieur'), ('LUXE', 'Luxe'), ('FAMILIALE', 'Familiale'), ('SUITE', 'Suite')], default='STANDARD', max_length=20)),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('photos_supplementaires', models.JSONField(blank=True, default=list)),
                ('capacite', models.IntegerField(default=2)),
                ('surface', models.IntegerField(blank=True, null=True)),
                ('equipements', models.JSONField(default=list)),
                ('nb_lits_simples', models.IntegerField(default=0)),
                ('nb_lits_doubles', models.IntegerField(default=1)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='api.hotel')),
            ],
            options={
                'ordering': ['-date_creation'],
                'unique_together': {('hotel', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.room'),
        ),
    ]
