# Generated by Django 6.1.1 on 2026-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la chambre'),
        ),
        migrations.AddField(
            model_name='room',
            name='nombre_avis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Note moyenne (0-5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacite',
            field=models.IntegerField(default=2, help_text='Nombre maximum de personnes'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipements',
            field=models.JSONField(default=list, help_text='Liste des équipements (WiFi, Clim, TV...)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Chambre activée par le propriétaire (visible aux clients)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='numero',
            field=models.CharField(help_text='Numéro de la chambre (ex: 101)', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='photos_supplementaires',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'URLs des photos supplémentaires"),
        ),
        migrations.AlterField(
            model_name='room',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=2, help_text='Prix par nuit en Ariary', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='surface',
            field=models.IntegerField(blank=True, help_text='Surface en m²', null=True),
        ),
    ]
